feeds:
- country: 新加坡
  fetch_jina: true
  media_group: 联合早报
  platform: 联合早报|国际新闻
  scrape_url: https://www.zaobao.com.sg/news/world
  time_only: true
  timeout: 30
  url: https://rss.app/feeds/NqwvqfwhwrKv9eya.xml
- country: 新加坡
  fetch_jina: true
  media_group: 联合早报
  platform: 联合早报|中国新闻
  scrape_url: https://www.zaobao.com.sg/news/china
  time_only: true
  timeout: 30
  url: https://rss.app/feeds/fKGzBfhuydHw3geo.xml
- country: 美国
  media_group: PBS
  platform: 美国政治
  timeout: 30
  url: https://rss.app/feeds/tR6OOiFleWnfeWvJ.xml
- country: 英国
  media_group: 路透社
  platform: 路透社|China
  timeout: 30
  url: https://rss.app/feeds/GoaYdKMysAJ2wh0N.xml
- country: 美国
  media_group: 路透社
  platform: 路透社|US
  timeout: 30
  url: https://rss.app/feeds/3SzXJwOJT9A9HLic.xml
- country: 英国
  media_group: 路透社
  platform: 路透社|x.com
  timeout: 30
  url: https://rss.app/feeds/pxSbEqhWbTfVocb4.xml
- country: 英国
  media_group: 路透社
  platform: 路透社|Japan
  timeout: 30
  url: https://rss.app/feeds/cCw9aLOr3IJQImEl.xml
- country: 美国
  media_group: 纽约时报
  platform: 纽约时报|china
  timeout: 30
  url: https://rss.app/feeds/vO1vKL4xXqrKIWab.xml
- country: 美国
  media_group: 纽约时报
  platform: 纽约时报|官网
  timeout: 30
  url: https://rss.app/feeds/MhUGsT90ZRDAUPyH.xml
- country: 美国
  media_group: CNN
  platform: CNN官网|world
  timeout: 30
  url: https://rss.app/feeds/vrnuIYnatTBL2WKe.xml
- country: 美国
  media_group: CNN
  platform: CNN|China
  timeout: 30
  url: https://rss.app/feeds/e6Epd6MGVavZouJl.xml
- country: 美国
  media_group: 华盛顿邮报
  platform: 'washingtonpost|White House '
  timeout: 30
  url: https://rss.app/feeds/MYOaR8UWegn5jyfc.xml
- country: 美国
  media_group: 华盛顿邮报
  platform: 'washingtonpost|White House '
  timeout: 30
  url: https://rss.app/feeds/ls6F732pV7N93OmE.xml
- country: 美国
  media_group: 华盛顿邮报
  platform: washingtonpost|Opinions
  timeout: 30
  url: https://rss.app/feeds/6MgtxEEQL3RAsMlL.xml
- country: 美国
  media_group: 美国众议议院（CCP）
  platform: 美国众议院
  timeout: 30
  url: https://rss.app/feeds/8gETqnSSE4IFWMuZ.xml
- country: 日本
  fetch_jina: false
  media_group: NHK
  platform: NHK（日本放送协会）
  scrape_url: https://www3.nhk.or.jp/nhkworld/zh/news/
  timeout: 30
  url: https://www3.nhk.or.jp/nhkworld/zh/news/
- country: 日本
  media_group: 共同社
  platform: 共同社 (Kyodo News)
  timeout: 30
  url: https://rss.app/feeds/O4AiW7fxDN6C6H5D.xml
- country: 英国
  media_group: BBC
  platform: BBC|x.com
  timeout: 30
  url: https://rss.app/feeds/9Rx7qXQGKoV0q4Dl.xml
- country: 英国
  media_group: BBC
  platform: Google News
  timeout: 30
  url: https://rss.app/feeds/yNjx9c29THw4aj5p.xml
- country: 日本
  media_group: 共同网
  platform: 共同网
  timeout: 30
  url: https://rss.app/feeds/9hfOqIWOIRYGxl9M.xml
- country: 韩国
  media_group: 韩联社
  platform: 韩联社
  timeout: 30
  url: https://rss.app/feeds/YNFZbio3L63ri2yv.xml
- country: 俄罗斯
  media_group: 俄罗斯卫星通信社
  platform: 俄罗斯卫星通信社
  timeout: 30
  url: https://rss.app/feeds/2s52rzRgdnH3g2j8.xml
- country: 美国
  media_group: 纽约时报
  platform: 纽约时报
  timeout: 30
  url: https://rss.app/feeds/EdaqV6KSPoxu0eya.xml
- country: 美国
  media_group: 彭博社
  platform: 彭博社
  timeout: 30
  url: https://rss.app/feeds/KeSi7yXakSMmBsZu.xml
- country: 日本
  media_group: 日经中文网
  platform: 日经中文网
  timeout: 30
  url: https://rss.app/feeds/k3QuxKgJEBSRF4Fw.xml
- country: 中国香港
  media_group: SCMP
  platform: 南华早报
  timeout: 30
  url: https://rss.app/feeds/dgewlTGu67rgE5XY.xml
- country: 中国香港
  media_group: SCMP
  platform: 南华早报
  timeout: 30
  url: https://rss.app/feeds/PwB79KgLHxoICdoS.xml
- country: 中国香港
  media_group: SCMP
  platform: 南华早报
  timeout: 30
  url: https://rss.app/feeds/7f6jueb2W7rXqz0V.xml
settings:
  auto_fetch: true
  interval_min: 20
  max_items: 2000
  similarity_threshold: 0.7
  summary_max_length: 200
  timeout: 30
